esphome:
  name: esp8266-gate
  friendly_name: esp8266-gate

esp8266:
  board: esp_wroom_02

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-Gate Fallback Hotspot"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

binary_sensor:
  # IN1
  - platform: gpio
    device_class: door
    icon: mdi:gate
    name: "Stan bramy"
    pin: GPIO14
    id: reedswitch
    publish_initial_state: True
    filters:
      - delayed_on: 1s

switch:
  - platform: gpio
    pin: GPIO5
    id: relay
    internal: True

button:
  - platform: template
    on_press:
      - switch.toggle: relay
      - delay: 500ms
      - switch.toggle: relay
    name: "Brama"
    icon: mdi:gate
